### PR TITLE
[work in progress] Tween animations for sliding doors

### PR DESCRIPTION
**Pull request by ndbroadbent**
I wanted some nice animations for my doors, so I found the [Tween.js library](https://github.com/tweenjs/tween.js). I've added it for my sliding doors so far, and I want to also add it for swing doors. Probably my lights too, and anything else that would look nice with smooth transitions.

https://user-images.githubusercontent.com/139536/189536235-7ecf5780-4e54-49fb-bd37-75e621c7dbfd.mov

### CODE REVIEW

**Comment by adizanni** [comment]
Very smooth and merges seamlessly in the code. You may generalize it to the rotate entity too.

**Comment by adizanni** [comment]
You are doing significant changes. It is porbably a good idea if we start putting the bases for a version 2.0

**Comment by uspass** [comment]
I'm working to tide up some loose ends on the code. I'll look asap.

**Comment by FragMenthor** [comment]
Thanks for this! How can we test it? Any instructions?

**Comment by ndbroadbent** [comment]
Hi @FragMenthor, this should be working for any sliding or swing doors without any extra setup. If you open or close a door, you should see the position change with an animated transition

**Comment by adizanni** [comment]
Hello @ndbroadbent I'm finally able to test a little, I found a few regressions introduced by the animations, I may try to open a bug or correct it directly into the code. Are you working on additional correction / enhancements ?.

**Comment by adizanni** [comment]
For the moment I'm testing using the obj format, becaus the glb format was very experimental and when I introduced it I discovered a number of impact on previously working functions. I thought I would work on making the obj and glb totally equivalent by nomalizing the model after the import in a way that all functions would behave exactly the same. But many of these things were planned to be integrated into v2.0. And to be honest I will not have time to dedicate to it in the forseeable future

**Comment by ndbroadbent** [comment]
@adizanni Sorry to hear about the regressions, please let me know if there are any bugs that I can help to fix!

I have moved onto some other projects for now so am not spending so much time on floor3d-card anymore, but I would like to make sure that everything is running smoothly and I haven't broken anything. Please let me know if there's anything I can help to fix or if anything needs to be reverted!

**Comment by adizanni** [comment]
helllo @ndbroadbent, nothing major, the doors that have hinges are not swinging anymore along the hinge axis but along the  door middle axis. No worries  and big thanks for all the enhancements.

**Comment by ndbroadbent** [comment]
Oops sorry about that, I will take a look! That's surprising though, all of my swing doors have hinges as well and it seems to be working for me. Would you be able to share an example I could look at?

**Comment by adizanni** [comment]
I may have missed something in the door config. If I can reproduce I will send you the example

**Pull request merged**
